### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by andre-idrive** [HakanL/DotNetTracking#1]
Will you be updating this soon? I just tired a FedEx tracking number but it came up as DHL when I used `TrackingType.GetMatches()`.

**Comment by HakanL** [comment]
No plans since there's been no issues reported until now. What's the tracking number so I can test? If the number is the same length for both DHL and FedEx then unfortunately there's no way to differential between which carrier, this package doesn't go out to any services, it's just using the numbers to determine the carrier.
