### ISSUE TITLE
.NETFramework v4.5.2?

### ISSUE THREAD

**Issue by TrexKikBut** [HakanL/DotNetTracking#2]
Hey, I was trying to use this package. But it isn't working with .NETFramework v4.5.2. is there a way to get it working?

**Comment by HakanL** [comment]
The library is built against .NET Standard, it may not be compatible with FW 452. You can probably just fork it and build it against 452, I don’t think I’m using any newer features in the code.

**Comment by dougwebb** [comment]
I just ran into this issue with a client who was trying to deploy a webapp targeting v4.6.1 to a server that doesn't have v4.7+ runtime installed. TrackingType.GetSequence returns a ValueTuple, which is only available in v4.7+.

You could add a TrackingSequence class with properties for Sequence and CheckDigit and return that instead (changing callers to do the unpacking manually), or you could make CheckDigit into an out method argument instead of part of the return type. I think the callers would need to declare CheckDigit separately rather than inline though, to be compatible with older .NET versions.

**Comment by HakanL** [comment]
If you submit a PR I can look into getting it merged in.

**Comment by HakanL** [comment]
This has been merged in, thanks for your contribution @dougwebb!

**Comment by dougwebb** [comment]
Thank you!
